[package]
name = "spfc-target-ttf"
version = "0.1.1"
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
spfc-abi = { path = "../../spfc-abi" }
write-fonts = "=0.45.0"
kurbo = "0.13.0"
bitvec = "1.0.1"
spf.workspace = true
render_spf.workspace = true
anyhow.workspace = true
chrono = "0.4.43"
unicode-segmentation = "1.12.0"