use crate::{builders::Process, utilities::{last_character_index, max_height, max_width}};
use anyhow::Result;

pub fn create_program_string(process: &Process) -> Result<String> {
    let mut program_string = String::new();

    program_string += "pico-8 cartridge // http://www.pico-8.com\nversion 41\n__lua__\n";

    program_string += format!("-- {} v{}\n-- {}\n-- Generated by spfc\n-- https://github.com/SimplePixelFont/spfc\n\n", process.family_name, process.family_version, process.manufacturer).as_str();

    let font_function = format!("load_{}", process.family_name.to_ascii_lowercase().replace(" ", "_"));
    program_string += format!("-- Copy the function below\n-- into your own cart\nfunction {}()\n\t-- enable custom fonts\n\tpoke(0x5f58,0x81)\n\n\t-- add font to memory\n", font_function).as_str();


    let mut buffer = vec![0; (last_character_index(&process.pixmap_pairs) as usize + 1) * 8];
    buffer[0] = max_width(&process.pixmap_pairs) + 1; //1 added for letter spacing
    buffer[1] = max_width(&process.pixmap_pairs); // This will be added as a custom flag
    buffer[2] = max_height(&process.pixmap_pairs) + 1; //1 added for line spacing
    buffer[3] = 0; // This will be added as a custom flag offset_x
    buffer[4] = 0; // This will be added as a custom flag offset_y

    for (key, glyph) in &process.pixmap_pairs {
        if let Some(p8_char) = crate::utilities::get_character_by_symbol(key) {
            let char_index = p8_char.id as usize;
            let bitmap_data = &glyph.bitmap;
            for (i, byte) in bitmap_data.iter().enumerate() {
                buffer[char_index * 8 + i] = *byte;
            }
        }
    }

    program_string += format!("\tpoke(0x5600,unpack(split\"{}\"))\nend\n\n", buffer.iter().map(|byte| byte.to_string()).collect::<Vec<String>>().join(",")).as_str();

    program_string += format!("-- Sample usage below\nfunction _init()\n\t{}()\nend\n\n", font_function).as_str();
    program_string += format!("function _draw()\n\tcls()\n\tprint(\"Hello from {}!\")\nend ", process.family_name).as_str();

    Ok(program_string)
}